server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/supermarket?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: 192.168.0.10
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired


supermarket:
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 20