server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/supermarket?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false