server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/supermarket?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

supermarket:
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000
  order:
    max-sku-limit: 777